Restore compatibility with GCC 7.5.0
This old compiler version (which is still used in the CI) apparently runs
into the following error:
```
CMakeFiles/pianobooster.dir/QtWindow.o: In function `QtWindow::updateRecentFileActions()':
QtWindow.cpp:(.text+0x4bd2): undefined reference to `QtWindow::MAX_RECENT_FILES'
```
Using a function should workaround this problem.